// src/services/mockData.js

export const mockData = {
    settings: [
        {
            id: "1",
            academicYear: "113",
            semester: "1",
            examName: "第三次定期考",
            uploadStart: "2026-03-25T00:00:00+08:00",
            uploadEnd: "2026-04-28T12:35:00+08:00",
            table: "exam1",
        },
        {
            id: "2",
            academicYear: "113",
            semester: "1",
            examName: "第二次定期考",
            uploadStart: "2025-11-01T00:00:00+08:00",
            uploadEnd: "2025-11-15T23:59:59+08:00",
            table: "exam2",
        },
    ],
    users: [
        {
            email: "admin@ksvs.kh.edu.tw",
            teacherCode: "A001",
            name: "王大明",
            role: "admin",
        },
        {
            email: "director@ksvs.kh.edu.tw",
            teacherCode: "A002",
            name: "林主任",
            role: "admin",
        },
        {
            email: "t1001@ksvs.kh.edu.tw",
            teacherCode: "T1001",
            name: "陳國文",
            role: "teacher",
        },
        {
            email: "t1002@ksvs.kh.edu.tw",
            teacherCode: "T1002",
            name: "李數學",
            role: "teacher",
        },
        {
            email: "t1003@ksvs.kh.edu.tw",
            teacherCode: "T1003",
            name: "張物理",
            role: "teacher",
        },
        {
            email: "t1004@ksvs.kh.edu.tw",
            teacherCode: "T1004",
            name: "吳健康",
            role: "teacher",
        },
        {
            email: "t2208@ksvs.kh.edu.tw",
            teacherCode: "T2208",
            name: "劉測試",
            role: "teacher",
        },
        {
            email: "t1005@ksvs.kh.edu.tw",
            teacherCode: "T1005",
            name: "教師5",
            role: "teacher",
        },
        {
            email: "t1006@ksvs.kh.edu.tw",
            teacherCode: "T1006",
            name: "教師6",
            role: "teacher",
        },
        {
            email: "t1007@ksvs.kh.edu.tw",
            teacherCode: "T1007",
            name: "教師7",
            role: "teacher",
        },
        {
            email: "t1008@ksvs.kh.edu.tw",
            teacherCode: "T1008",
            name: "教師8",
            role: "teacher",
        },
        {
            email: "t1009@ksvs.kh.edu.tw",
            teacherCode: "T1009",
            name: "教師9",
            role: "teacher",
        },
        {
            email: "t1010@ksvs.kh.edu.tw",
            teacherCode: "T1010",
            name: "教師10",
            role: "teacher",
        },
        {
            email: "t1011@ksvs.kh.edu.tw",
            teacherCode: "T1011",
            name: "教師11",
            role: "teacher",
        },
        {
            email: "t1012@ksvs.kh.edu.tw",
            teacherCode: "T1012",
            name: "教師12",
            role: "teacher",
        },
        {
            email: "t1013@ksvs.kh.edu.tw",
            teacherCode: "T1013",
            name: "教師13",
            role: "teacher",
        },
        {
            email: "t1014@ksvs.kh.edu.tw",
            teacherCode: "T1014",
            name: "教師14",
            role: "teacher",
        },
        {
            email: "t1015@ksvs.kh.edu.tw",
            teacherCode: "T1015",
            name: "教師15",
            role: "teacher",
        },
        {
            email: "t1016@ksvs.kh.edu.tw",
            teacherCode: "T1016",
            name: "教師16",
            role: "teacher",
        },
        {
            email: "t1017@ksvs.kh.edu.tw",
            teacherCode: "T1017",
            name: "教師17",
            role: "teacher",
        },
        {
            email: "t1018@ksvs.kh.edu.tw",
            teacherCode: "T1018",
            name: "教師18",
            role: "teacher",
        },
        {
            email: "t1019@ksvs.kh.edu.tw",
            teacherCode: "T1019",
            name: "教師19",
            role: "teacher",
        },
        {
            email: "t1020@ksvs.kh.edu.tw",
            teacherCode: "T1020",
            name: "教師20",
            role: "teacher",
        },
        {
            email: "t1021@ksvs.kh.edu.tw",
            teacherCode: "T1021",
            name: "教師21",
            role: "teacher",
        },
        {
            email: "t1022@ksvs.kh.edu.tw",
            teacherCode: "T1022",
            name: "教師22",
            role: "teacher",
        },
        {
            email: "t1023@ksvs.kh.edu.tw",
            teacherCode: "T1023",
            name: "教師23",
            role: "teacher",
        },
        {
            email: "t1024@ksvs.kh.edu.tw",
            teacherCode: "T1024",
            name: "教師24",
            role: "teacher",
        },
        {
            email: "t1025@ksvs.kh.edu.tw",
            teacherCode: "T1025",
            name: "教師25",
            role: "teacher",
        },
        {
            email: "t1026@ksvs.kh.edu.tw",
            teacherCode: "T1026",
            name: "教師26",
            role: "teacher",
        },
        {
            email: "t1027@ksvs.kh.edu.tw",
            teacherCode: "T1027",
            name: "教師27",
            role: "teacher",
        },
        {
            email: "t1028@ksvs.kh.edu.tw",
            teacherCode: "T1028",
            name: "教師28",
            role: "teacher",
        },
        {
            email: "t1029@ksvs.kh.edu.tw",
            teacherCode: "T1029",
            name: "教師29",
            role: "teacher",
        },
        {
            email: "t1030@ksvs.kh.edu.tw",
            teacherCode: "T1030",
            name: "教師30",
            role: "teacher",
        },
        {
            email: "t1031@ksvs.kh.edu.tw",
            teacherCode: "T1031",
            name: "教師31",
            role: "teacher",
        },
        {
            email: "t1032@ksvs.kh.edu.tw",
            teacherCode: "T1032",
            name: "教師32",
            role: "teacher",
        },
        {
            email: "t1033@ksvs.kh.edu.tw",
            teacherCode: "T1033",
            name: "教師33",
            role: "teacher",
        },
        {
            email: "t1034@ksvs.kh.edu.tw",
            teacherCode: "T1034",
            name: "教師34",
            role: "teacher",
        },
        {
            email: "t1035@ksvs.kh.edu.tw",
            teacherCode: "T1035",
            name: "教師35",
            role: "teacher",
        },
        {
            email: "t1036@ksvs.kh.edu.tw",
            teacherCode: "T1036",
            name: "教師36",
            role: "teacher",
        },
        {
            email: "t1037@ksvs.kh.edu.tw",
            teacherCode: "T1037",
            name: "教師37",
            role: "teacher",
        },
        {
            email: "t1038@ksvs.kh.edu.tw",
            teacherCode: "T1038",
            name: "教師38",
            role: "teacher",
        },
        {
            email: "t1039@ksvs.kh.edu.tw",
            teacherCode: "T1039",
            name: "教師39",
            role: "teacher",
        },
        {
            email: "t1040@ksvs.kh.edu.tw",
            teacherCode: "T1040",
            name: "教師40",
            role: "teacher",
        },
        {
            email: "t1041@ksvs.kh.edu.tw",
            teacherCode: "T1041",
            name: "教師41",
            role: "teacher",
        },
        {
            email: "t1042@ksvs.kh.edu.tw",
            teacherCode: "T1042",
            name: "教師42",
            role: "teacher",
        },
        {
            email: "t1043@ksvs.kh.edu.tw",
            teacherCode: "T1043",
            name: "教師43",
            role: "teacher",
        },
        {
            email: "t1044@ksvs.kh.edu.tw",
            teacherCode: "T1044",
            name: "教師44",
            role: "teacher",
        },
        {
            email: "t1045@ksvs.kh.edu.tw",
            teacherCode: "T1045",
            name: "教師45",
            role: "teacher",
        },
        {
            email: "t1046@ksvs.kh.edu.tw",
            teacherCode: "T1046",
            name: "教師46",
            role: "teacher",
        },
        {
            email: "t1047@ksvs.kh.edu.tw",
            teacherCode: "T1047",
            name: "教師47",
            role: "teacher",
        },
        {
            email: "t1048@ksvs.kh.edu.tw",
            teacherCode: "T1048",
            name: "教師48",
            role: "teacher",
        },
        {
            email: "t1049@ksvs.kh.edu.tw",
            teacherCode: "T1049",
            name: "教師49",
            role: "teacher",
        },
        {
            email: "t1050@ksvs.kh.edu.tw",
            teacherCode: "T1050",
            name: "教師50",
            role: "teacher",
        },
        {
            email: "t1051@ksvs.kh.edu.tw",
            teacherCode: "T1051",
            name: "教師51",
            role: "teacher",
        },
        {
            email: "t1052@ksvs.kh.edu.tw",
            teacherCode: "T1052",
            name: "教師52",
            role: "teacher",
        },
        {
            email: "t1053@ksvs.kh.edu.tw",
            teacherCode: "T1053",
            name: "教師53",
            role: "teacher",
        },
        {
            email: "t1054@ksvs.kh.edu.tw",
            teacherCode: "T1054",
            name: "教師54",
            role: "teacher",
        },
        {
            email: "t1055@ksvs.kh.edu.tw",
            teacherCode: "T1055",
            name: "教師55",
            role: "teacher",
        },
        {
            email: "t1056@ksvs.kh.edu.tw",
            teacherCode: "T1056",
            name: "教師56",
            role: "teacher",
        },
        {
            email: "t1057@ksvs.kh.edu.tw",
            teacherCode: "T1057",
            name: "教師57",
            role: "teacher",
        },
        {
            email: "t1058@ksvs.kh.edu.tw",
            teacherCode: "T1058",
            name: "教師58",
            role: "teacher",
        },
        {
            email: "t1059@ksvs.kh.edu.tw",
            teacherCode: "T1059",
            name: "教師59",
            role: "teacher",
        },
        {
            email: "t1060@ksvs.kh.edu.tw",
            teacherCode: "T1060",
            name: "教師60",
            role: "teacher",
        },
        {
            email: "t1061@ksvs.kh.edu.tw",
            teacherCode: "T1061",
            name: "教師61",
            role: "teacher",
        },
        {
            email: "t1062@ksvs.kh.edu.tw",
            teacherCode: "T1062",
            name: "教師62",
            role: "teacher",
        },
        {
            email: "t1063@ksvs.kh.edu.tw",
            teacherCode: "T1063",
            name: "教師63",
            role: "teacher",
        },
        {
            email: "t1064@ksvs.kh.edu.tw",
            teacherCode: "T1064",
            name: "教師64",
            role: "teacher",
        },
        {
            email: "t1065@ksvs.kh.edu.tw",
            teacherCode: "T1065",
            name: "教師65",
            role: "teacher",
        },
        {
            email: "t1066@ksvs.kh.edu.tw",
            teacherCode: "T1066",
            name: "教師66",
            role: "teacher",
        },
        {
            email: "t1067@ksvs.kh.edu.tw",
            teacherCode: "T1067",
            name: "教師67",
            role: "teacher",
        },
        {
            email: "t1068@ksvs.kh.edu.tw",
            teacherCode: "T1068",
            name: "教師68",
            role: "teacher",
        },
        {
            email: "t1069@ksvs.kh.edu.tw",
            teacherCode: "T1069",
            name: "教師69",
            role: "teacher",
        },
        {
            email: "t1070@ksvs.kh.edu.tw",
            teacherCode: "T1070",
            name: "教師70",
            role: "teacher",
        },
        {
            email: "t1071@ksvs.kh.edu.tw",
            teacherCode: "T1071",
            name: "教師71",
            role: "teacher",
        },
        {
            email: "t1072@ksvs.kh.edu.tw",
            teacherCode: "T1072",
            name: "教師72",
            role: "teacher",
        },
        {
            email: "t1073@ksvs.kh.edu.tw",
            teacherCode: "T1073",
            name: "教師73",
            role: "teacher",
        },
        {
            email: "t1074@ksvs.kh.edu.tw",
            teacherCode: "T1074",
            name: "教師74",
            role: "teacher",
        },
        {
            email: "t1075@ksvs.kh.edu.tw",
            teacherCode: "T1075",
            name: "教師75",
            role: "teacher",
        },
        {
            email: "t1076@ksvs.kh.edu.tw",
            teacherCode: "T1076",
            name: "教師76",
            role: "teacher",
        },
        {
            email: "t1077@ksvs.kh.edu.tw",
            teacherCode: "T1077",
            name: "教師77",
            role: "teacher",
        },
        {
            email: "t1078@ksvs.kh.edu.tw",
            teacherCode: "T1078",
            name: "教師78",
            role: "teacher",
        },
        {
            email: "t1079@ksvs.kh.edu.tw",
            teacherCode: "T1079",
            name: "教師79",
            role: "teacher",
        },
        {
            email: "t1080@ksvs.kh.edu.tw",
            teacherCode: "T1080",
            name: "教師80",
            role: "teacher",
        },
        {
            email: "t1081@ksvs.kh.edu.tw",
            teacherCode: "T1081",
            name: "教師81",
            role: "teacher",
        },
        {
            email: "t1082@ksvs.kh.edu.tw",
            teacherCode: "T1082",
            name: "教師82",
            role: "teacher",
        },
        {
            email: "t1083@ksvs.kh.edu.tw",
            teacherCode: "T1083",
            name: "教師83",
            role: "teacher",
        },
        {
            email: "t1084@ksvs.kh.edu.tw",
            teacherCode: "T1084",
            name: "教師84",
            role: "teacher",
        },
        {
            email: "t1085@ksvs.kh.edu.tw",
            teacherCode: "T1085",
            name: "教師85",
            role: "teacher",
        },
        {
            email: "t1086@ksvs.kh.edu.tw",
            teacherCode: "T1086",
            name: "教師86",
            role: "teacher",
        },
        {
            email: "t1087@ksvs.kh.edu.tw",
            teacherCode: "T1087",
            name: "教師87",
            role: "teacher",
        },
        {
            email: "t1088@ksvs.kh.edu.tw",
            teacherCode: "T1088",
            name: "教師88",
            role: "teacher",
        },
        {
            email: "t1089@ksvs.kh.edu.tw",
            teacherCode: "T1089",
            name: "教師89",
            role: "teacher",
        },
        {
            email: "t1090@ksvs.kh.edu.tw",
            teacherCode: "T1090",
            name: "教師90",
            role: "teacher",
        },
        {
            email: "t1091@ksvs.kh.edu.tw",
            teacherCode: "T1091",
            name: "教師91",
            role: "teacher",
        },
        {
            email: "t1092@ksvs.kh.edu.tw",
            teacherCode: "T1092",
            name: "教師92",
            role: "teacher",
        },
        {
            email: "t1093@ksvs.kh.edu.tw",
            teacherCode: "T1093",
            name: "教師93",
            role: "teacher",
        },
        {
            email: "t1094@ksvs.kh.edu.tw",
            teacherCode: "T1094",
            name: "教師94",
            role: "teacher",
        },
        {
            email: "t1095@ksvs.kh.edu.tw",
            teacherCode: "T1095",
            name: "教師95",
            role: "teacher",
        },
        {
            email: "t1096@ksvs.kh.edu.tw",
            teacherCode: "T1096",
            name: "教師96",
            role: "teacher",
        },
        {
            email: "t1097@ksvs.kh.edu.tw",
            teacherCode: "T1097",
            name: "教師97",
            role: "teacher",
        },
        {
            email: "t1098@ksvs.kh.edu.tw",
            teacherCode: "T1098",
            name: "教師98",
            role: "teacher",
        },
        {
            email: "t1099@ksvs.kh.edu.tw",
            teacherCode: "T1099",
            name: "教師99",
            role: "teacher",
        },
        {
            email: "t1100@ksvs.kh.edu.tw",
            teacherCode: "T1100",
            name: "教師100",
            role: "teacher",
        },
        {
            email: "t1101@ksvs.kh.edu.tw",
            teacherCode: "T1101",
            name: "教師101",
            role: "teacher",
        },
        {
            email: "t1102@ksvs.kh.edu.tw",
            teacherCode: "T1102",
            name: "教師102",
            role: "teacher",
        },
        {
            email: "t1103@ksvs.kh.edu.tw",
            teacherCode: "T1103",
            name: "教師103",
            role: "teacher",
        },
        {
            email: "t1104@ksvs.kh.edu.tw",
            teacherCode: "T1104",
            name: "教師104",
            role: "teacher",
        },
        {
            email: "t1105@ksvs.kh.edu.tw",
            teacherCode: "T1105",
            name: "教師105",
            role: "teacher",
        },
        {
            email: "t1106@ksvs.kh.edu.tw",
            teacherCode: "T1106",
            name: "教師106",
            role: "teacher",
        },
        {
            email: "t1107@ksvs.kh.edu.tw",
            teacherCode: "T1107",
            name: "教師107",
            role: "teacher",
        },
        {
            email: "t1108@ksvs.kh.edu.tw",
            teacherCode: "T1108",
            name: "教師108",
            role: "teacher",
        },
        {
            email: "t1109@ksvs.kh.edu.tw",
            teacherCode: "T1109",
            name: "教師109",
            role: "teacher",
        },
        {
            email: "t1110@ksvs.kh.edu.tw",
            teacherCode: "T1110",
            name: "教師110",
            role: "teacher",
        },
    ],
    classes: [
        {
            id: "101",
            name: "機械一甲",
        },
        {
            id: "102",
            name: "資訊一甲",
        },
        {
            id: "201",
            name: "電機二甲",
        },
        {
            id: "301",
            name: "電子三甲",
        },
        {
            id: "2",
            name: "機械一乙",
        },
        {
            id: "3",
            name: "機械一丙",
        },
        {
            id: "4",
            name: "機械一丁",
        },
        {
            id: "6",
            name: "資訊一乙",
        },
        {
            id: "7",
            name: "資訊一丙",
        },
        {
            id: "8",
            name: "資訊一丁",
        },
        {
            id: "9",
            name: "電子一甲",
        },
        {
            id: "10",
            name: "電子一乙",
        },
        {
            id: "11",
            name: "電子一丙",
        },
        {
            id: "12",
            name: "電子一丁",
        },
        {
            id: "13",
            name: "電機一甲",
        },
        {
            id: "14",
            name: "電機一乙",
        },
        {
            id: "15",
            name: "電機一丙",
        },
        {
            id: "16",
            name: "電機一丁",
        },
        {
            id: "17",
            name: "化工一甲",
        },
        {
            id: "18",
            name: "化工一乙",
        },
        {
            id: "19",
            name: "化工一丙",
        },
        {
            id: "20",
            name: "化工一丁",
        },
        {
            id: "21",
            name: "土木一甲",
        },
        {
            id: "22",
            name: "土木一乙",
        },
        {
            id: "23",
            name: "土木一丙",
        },
        {
            id: "24",
            name: "土木一丁",
        },
        {
            id: "25",
            name: "建築一甲",
        },
        {
            id: "26",
            name: "建築一乙",
        },
        {
            id: "27",
            name: "建築一丙",
        },
        {
            id: "28",
            name: "建築一丁",
        },
        {
            id: "29",
            name: "美工一甲",
        },
        {
            id: "30",
            name: "美工一乙",
        },
        {
            id: "31",
            name: "美工一丙",
        },
        {
            id: "32",
            name: "美工一丁",
        },
        {
            id: "33",
            name: "室設一甲",
        },
        {
            id: "34",
            name: "室設一乙",
        },
        {
            id: "35",
            name: "室設一丙",
        },
        {
            id: "36",
            name: "室設一丁",
        },
        {
            id: "37",
            name: "機械二甲",
        },
        {
            id: "38",
            name: "機械二乙",
        },
        {
            id: "39",
            name: "機械二丙",
        },
        {
            id: "40",
            name: "機械二丁",
        },
        {
            id: "41",
            name: "資訊二甲",
        },
        {
            id: "42",
            name: "資訊二乙",
        },
        {
            id: "43",
            name: "資訊二丙",
        },
        {
            id: "44",
            name: "資訊二丁",
        },
        {
            id: "45",
            name: "電子二甲",
        },
        {
            id: "46",
            name: "電子二乙",
        },
        {
            id: "47",
            name: "電子二丙",
        },
        {
            id: "48",
            name: "電子二丁",
        },
        {
            id: "50",
            name: "電機二乙",
        },
        {
            id: "51",
            name: "電機二丙",
        },
        {
            id: "52",
            name: "電機二丁",
        },
        {
            id: "53",
            name: "化工二甲",
        },
        {
            id: "54",
            name: "化工二乙",
        },
        {
            id: "55",
            name: "化工二丙",
        },
        {
            id: "56",
            name: "化工二丁",
        },
        {
            id: "57",
            name: "土木二甲",
        },
        {
            id: "58",
            name: "土木二乙",
        },
        {
            id: "59",
            name: "土木二丙",
        },
        {
            id: "60",
            name: "土木二丁",
        },
        {
            id: "61",
            name: "建築二甲",
        },
        {
            id: "62",
            name: "建築二乙",
        },
        {
            id: "63",
            name: "建築二丙",
        },
        {
            id: "64",
            name: "建築二丁",
        },
        {
            id: "65",
            name: "美工二甲",
        },
        {
            id: "66",
            name: "美工二乙",
        },
        {
            id: "67",
            name: "美工二丙",
        },
        {
            id: "68",
            name: "美工二丁",
        },
        {
            id: "69",
            name: "室設二甲",
        },
        {
            id: "70",
            name: "室設二乙",
        },
        {
            id: "71",
            name: "室設二丙",
        },
        {
            id: "72",
            name: "室設二丁",
        },
        {
            id: "73",
            name: "機械三甲",
        },
        {
            id: "74",
            name: "機械三乙",
        },
        {
            id: "75",
            name: "機械三丙",
        },
        {
            id: "76",
            name: "機械三丁",
        },
        {
            id: "77",
            name: "資訊三甲",
        },
        {
            id: "78",
            name: "資訊三乙",
        },
        {
            id: "79",
            name: "資訊三丙",
        },
        {
            id: "80",
            name: "資訊三丁",
        },
        {
            id: "82",
            name: "電子三乙",
        },
        {
            id: "83",
            name: "電子三丙",
        },
        {
            id: "84",
            name: "電子三丁",
        },
        {
            id: "85",
            name: "電機三甲",
        },
        {
            id: "86",
            name: "電機三乙",
        },
        {
            id: "87",
            name: "電機三丙",
        },
        {
            id: "88",
            name: "電機三丁",
        },
        {
            id: "89",
            name: "化工三甲",
        },
        {
            id: "90",
            name: "化工三乙",
        },
        {
            id: "91",
            name: "化工三丙",
        },
        {
            id: "92",
            name: "化工三丁",
        },
        {
            id: "93",
            name: "土木三甲",
        },
        {
            id: "94",
            name: "土木三乙",
        },
        {
            id: "95",
            name: "土木三丙",
        },
        {
            id: "96",
            name: "土木三丁",
        },
        {
            id: "97",
            name: "建築三甲",
        },
        {
            id: "98",
            name: "建築三乙",
        },
        {
            id: "99",
            name: "建築三丙",
        },
        {
            id: "100",
            name: "建築三丁",
        },
    ],
    exam1: [
        {
            id: "e1_1",
            department: "共同科目",
            grade: 1,
            subject: "英語文",
            teacherEmail: "t1001@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械一甲, 資訊一甲, 電子一甲, 電機一乙",
            hasListeningExam: false,
        },
        {
            id: "e1_5",
            department: "共同科目",
            grade: 1,
            subject: "國語文",
            teacherEmail: "t1001@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "人工閱卷+電腦閱卷",
            pageCount: 0,
            applicableClass: "全一年級",
        },
        {
            id: "e1_6",
            department: "共同科目",
            grade: 2,
            subject: "歷史",
            teacherEmail: "t1001@ksvs.kh.edu.tw",
            fileUrl: "https://example.com/mock.pdf",
            markingType: "電腦閱卷",
            pageCount: 2,
            applicableClass: "二甲, 二乙, 二丙",
        },
        {
            id: "e1_3",
            department: "共同科目",
            grade: 3,
            subject: "數學",
            teacherEmail: "t1017@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_5",
            department: "共同科目",
            grade: 3,
            subject: "地理",
            teacherEmail: "t1107@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_6",
            department: "共同科目",
            grade: 1,
            subject: "公民",
            teacherEmail: "t1067@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_7",
            department: "共同科目",
            grade: 3,
            subject: "物理",
            teacherEmail: "t1012@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_8",
            department: "共同科目",
            grade: 3,
            subject: "化學",
            teacherEmail: "t1030@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_9",
            department: "共同科目",
            grade: 3,
            subject: "生物",
            teacherEmail: "t1009@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_10",
            department: "共同科目",
            grade: 1,
            subject: "地科",
            teacherEmail: "t1084@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_11",
            department: "機械群",
            grade: 2,
            subject: "機械原理",
            teacherEmail: "t1037@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_12",
            department: "機械群",
            grade: 1,
            subject: "機械力學",
            teacherEmail: "t1023@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_13",
            department: "機械群",
            grade: 2,
            subject: "機械製造",
            teacherEmail: "t1101@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_14",
            department: "機械群",
            grade: 2,
            subject: "機械設計",
            teacherEmail: "t1049@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_15",
            department: "機械群",
            grade: 3,
            subject: "電腦繪圖",
            teacherEmail: "t1003@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_16",
            department: "電機電子群",
            grade: 3,
            subject: "電工原理",
            teacherEmail: "t1032@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_17",
            department: "電機電子群",
            grade: 1,
            subject: "電子學",
            teacherEmail: "t1055@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_18",
            department: "電機電子群",
            grade: 1,
            subject: "數位邏輯",
            teacherEmail: "t1096@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_19",
            department: "電機電子群",
            grade: 2,
            subject: "單晶片控制",
            teacherEmail: "t1027@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_20",
            department: "電機電子群",
            grade: 3,
            subject: "微處理機",
            teacherEmail: "t1039@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_21",
            department: "資訊群",
            grade: 2,
            subject: "程式設計 (21)",
            teacherEmail: "t1037@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_22",
            department: "資訊群",
            grade: 3,
            subject: "資料結構 (22)",
            teacherEmail: "t1024@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_23",
            department: "資訊群",
            grade: 2,
            subject: "演算法 (23)",
            teacherEmail: "t1069@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_24",
            department: "資訊群",
            grade: 1,
            subject: "計算機概論 (24)",
            teacherEmail: "t1063@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_25",
            department: "資訊群",
            grade: 2,
            subject: "資料庫管理 (25)",
            teacherEmail: "t1054@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_26",
            department: "共同科目",
            grade: 3,
            subject: "國語文 (26)",
            teacherEmail: "t1048@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_27",
            department: "共同科目",
            grade: 3,
            subject: "英語文 (27)",
            teacherEmail: "t1010@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_28",
            department: "共同科目",
            grade: 1,
            subject: "數學 (28)",
            teacherEmail: "t1002@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_29",
            department: "共同科目",
            grade: 2,
            subject: "歷史 (29)",
            teacherEmail: "t1078@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_30",
            department: "共同科目",
            grade: 1,
            subject: "地理 (30)",
            teacherEmail: "t1090@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_31",
            department: "共同科目",
            grade: 3,
            subject: "公民 (31)",
            teacherEmail: "t1104@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_32",
            department: "共同科目",
            grade: 3,
            subject: "物理 (32)",
            teacherEmail: "t1043@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_33",
            department: "共同科目",
            grade: 1,
            subject: "化學 (33)",
            teacherEmail: "t1017@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_34",
            department: "共同科目",
            grade: 3,
            subject: "生物 (34)",
            teacherEmail: "t1050@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_35",
            department: "共同科目",
            grade: 2,
            subject: "地科 (35)",
            teacherEmail: "t1105@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_36",
            department: "機械群",
            grade: 1,
            subject: "機械原理 (36)",
            teacherEmail: "t1023@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_37",
            department: "機械群",
            grade: 2,
            subject: "機械力學 (37)",
            teacherEmail: "t1014@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_38",
            department: "機械群",
            grade: 2,
            subject: "機械製造 (38)",
            teacherEmail: "t1082@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_39",
            department: "機械群",
            grade: 1,
            subject: "機械設計 (39)",
            teacherEmail: "t1085@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_40",
            department: "機械群",
            grade: 1,
            subject: "電腦繪圖 (40)",
            teacherEmail: "t1032@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_41",
            department: "電機電子群",
            grade: 1,
            subject: "電工原理 (41)",
            teacherEmail: "t1043@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_42",
            department: "電機電子群",
            grade: 3,
            subject: "電子學 (42)",
            teacherEmail: "t1055@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_43",
            department: "電機電子群",
            grade: 1,
            subject: "數位邏輯 (43)",
            teacherEmail: "t1070@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_44",
            department: "電機電子群",
            grade: 3,
            subject: "單晶片控制 (44)",
            teacherEmail: "t1100@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_45",
            department: "電機電子群",
            grade: 2,
            subject: "微處理機 (45)",
            teacherEmail: "t1054@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_46",
            department: "資訊群",
            grade: 2,
            subject: "程式設計 (46)",
            teacherEmail: "t1017@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_47",
            department: "資訊群",
            grade: 2,
            subject: "資料結構 (47)",
            teacherEmail: "t1027@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_48",
            department: "資訊群",
            grade: 1,
            subject: "演算法 (48)",
            teacherEmail: "t1072@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_49",
            department: "資訊群",
            grade: 3,
            subject: "計算機概論 (49)",
            teacherEmail: "t1072@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_50",
            department: "資訊群",
            grade: 3,
            subject: "資料庫管理 (50)",
            teacherEmail: "t1014@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_51",
            department: "共同科目",
            grade: 2,
            subject: "國語文 (51)",
            teacherEmail: "t1053@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_52",
            department: "共同科目",
            grade: 2,
            subject: "英語文 (52)",
            teacherEmail: "t1053@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_53",
            department: "共同科目",
            grade: 1,
            subject: "數學 (53)",
            teacherEmail: "t1028@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_54",
            department: "共同科目",
            grade: 2,
            subject: "歷史 (54)",
            teacherEmail: "t1012@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_55",
            department: "共同科目",
            grade: 1,
            subject: "地理 (55)",
            teacherEmail: "t1097@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_56",
            department: "共同科目",
            grade: 2,
            subject: "公民 (56)",
            teacherEmail: "t1017@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_57",
            department: "共同科目",
            grade: 3,
            subject: "物理 (57)",
            teacherEmail: "t1030@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_58",
            department: "共同科目",
            grade: 2,
            subject: "化學 (58)",
            teacherEmail: "t1006@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_59",
            department: "共同科目",
            grade: 3,
            subject: "生物 (59)",
            teacherEmail: "t1030@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_60",
            department: "共同科目",
            grade: 1,
            subject: "地科 (60)",
            teacherEmail: "t1099@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_61",
            department: "機械群",
            grade: 1,
            subject: "機械原理 (61)",
            teacherEmail: "t1107@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_62",
            department: "機械群",
            grade: 2,
            subject: "機械力學 (62)",
            teacherEmail: "t1103@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_63",
            department: "機械群",
            grade: 2,
            subject: "機械製造 (63)",
            teacherEmail: "t1084@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_64",
            department: "機械群",
            grade: 3,
            subject: "機械設計 (64)",
            teacherEmail: "t1108@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_65",
            department: "機械群",
            grade: 1,
            subject: "電腦繪圖 (65)",
            teacherEmail: "t1060@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_66",
            department: "電機電子群",
            grade: 2,
            subject: "電工原理 (66)",
            teacherEmail: "t1106@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_67",
            department: "電機電子群",
            grade: 1,
            subject: "電子學 (67)",
            teacherEmail: "t1047@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_68",
            department: "電機電子群",
            grade: 2,
            subject: "數位邏輯 (68)",
            teacherEmail: "t1080@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_69",
            department: "電機電子群",
            grade: 1,
            subject: "單晶片控制 (69)",
            teacherEmail: "t1104@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_70",
            department: "電機電子群",
            grade: 1,
            subject: "微處理機 (70)",
            teacherEmail: "t1070@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_71",
            department: "資訊群",
            grade: 1,
            subject: "程式設計 (71)",
            teacherEmail: "t1045@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_72",
            department: "資訊群",
            grade: 2,
            subject: "資料結構 (72)",
            teacherEmail: "t1003@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_73",
            department: "資訊群",
            grade: 2,
            subject: "演算法 (73)",
            teacherEmail: "t1030@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_74",
            department: "資訊群",
            grade: 2,
            subject: "計算機概論 (74)",
            teacherEmail: "t1004@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_75",
            department: "資訊群",
            grade: 2,
            subject: "資料庫管理 (75)",
            teacherEmail: "t1061@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_76",
            department: "共同科目",
            grade: 2,
            subject: "國語文 (76)",
            teacherEmail: "t1098@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_77",
            department: "共同科目",
            grade: 3,
            subject: "英語文 (77)",
            teacherEmail: "t1031@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_78",
            department: "共同科目",
            grade: 3,
            subject: "數學 (78)",
            teacherEmail: "t1098@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_79",
            department: "共同科目",
            grade: 1,
            subject: "歷史 (79)",
            teacherEmail: "t1031@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_80",
            department: "共同科目",
            grade: 2,
            subject: "地理 (80)",
            teacherEmail: "t1076@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_81",
            department: "共同科目",
            grade: 1,
            subject: "公民 (81)",
            teacherEmail: "t1033@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_82",
            department: "共同科目",
            grade: 2,
            subject: "物理 (82)",
            teacherEmail: "t1070@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_83",
            department: "共同科目",
            grade: 2,
            subject: "化學 (83)",
            teacherEmail: "t1108@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_84",
            department: "共同科目",
            grade: 1,
            subject: "生物 (84)",
            teacherEmail: "t1106@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_85",
            department: "共同科目",
            grade: 1,
            subject: "地科 (85)",
            teacherEmail: "t1013@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_86",
            department: "機械群",
            grade: 3,
            subject: "機械原理 (86)",
            teacherEmail: "t1020@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_87",
            department: "機械群",
            grade: 3,
            subject: "機械力學 (87)",
            teacherEmail: "t1106@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_88",
            department: "機械群",
            grade: 2,
            subject: "機械製造 (88)",
            teacherEmail: "t1060@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_89",
            department: "機械群",
            grade: 1,
            subject: "機械設計 (89)",
            teacherEmail: "t1100@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_90",
            department: "機械群",
            grade: 1,
            subject: "電腦繪圖 (90)",
            teacherEmail: "t1029@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_91",
            department: "電機電子群",
            grade: 3,
            subject: "電工原理 (91)",
            teacherEmail: "t1023@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_92",
            department: "電機電子群",
            grade: 1,
            subject: "電子學 (92)",
            teacherEmail: "t1016@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_93",
            department: "電機電子群",
            grade: 2,
            subject: "數位邏輯 (93)",
            teacherEmail: "t1042@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_94",
            department: "電機電子群",
            grade: 3,
            subject: "單晶片控制 (94)",
            teacherEmail: "t1059@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_95",
            department: "電機電子群",
            grade: 3,
            subject: "微處理機 (95)",
            teacherEmail: "t1021@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_96",
            department: "資訊群",
            grade: 3,
            subject: "程式設計 (96)",
            teacherEmail: "t1006@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_97",
            department: "資訊群",
            grade: 3,
            subject: "資料結構 (97)",
            teacherEmail: "t1072@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_98",
            department: "資訊群",
            grade: 1,
            subject: "演算法 (98)",
            teacherEmail: "t1037@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_99",
            department: "資訊群",
            grade: 2,
            subject: "計算機概論 (99)",
            teacherEmail: "t1059@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_100",
            department: "資訊群",
            grade: 3,
            subject: "資料庫管理 (100)",
            teacherEmail: "t1031@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "資訊群三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_101",
            department: "共同科目",
            grade: 3,
            subject: "國語文 (101)",
            teacherEmail: "t1053@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_102",
            department: "共同科目",
            grade: 2,
            subject: "英語文 (102)",
            teacherEmail: "t1022@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_103",
            department: "共同科目",
            grade: 2,
            subject: "數學 (103)",
            teacherEmail: "t1054@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_104",
            department: "共同科目",
            grade: 3,
            subject: "歷史 (104)",
            teacherEmail: "t1063@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_105",
            department: "共同科目",
            grade: 3,
            subject: "地理 (105)",
            teacherEmail: "t1090@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_106",
            department: "共同科目",
            grade: 1,
            subject: "公民 (106)",
            teacherEmail: "t1110@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_107",
            department: "共同科目",
            grade: 2,
            subject: "物理 (107)",
            teacherEmail: "t1019@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_108",
            department: "共同科目",
            grade: 3,
            subject: "化學 (108)",
            teacherEmail: "t1098@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_109",
            department: "共同科目",
            grade: 2,
            subject: "生物 (109)",
            teacherEmail: "t1071@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_110",
            department: "共同科目",
            grade: 3,
            subject: "地科 (110)",
            teacherEmail: "t1030@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "共同科目三各班",
            hasListeningExam: false,
        },
        {
            id: "e1_111",
            department: "機械群",
            grade: 1,
            subject: "機械原理 (111)",
            teacherEmail: "t1108@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_112",
            department: "機械群",
            grade: 2,
            subject: "機械力學 (112)",
            teacherEmail: "t1068@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_113",
            department: "機械群",
            grade: 2,
            subject: "機械製造 (113)",
            teacherEmail: "t1058@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_114",
            department: "機械群",
            grade: 2,
            subject: "機械設計 (114)",
            teacherEmail: "t1003@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_115",
            department: "機械群",
            grade: 2,
            subject: "電腦繪圖 (115)",
            teacherEmail: "t1016@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "機械群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_116",
            department: "電機電子群",
            grade: 2,
            subject: "電工原理 (116)",
            teacherEmail: "t1086@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群二各班",
            hasListeningExam: false,
        },
        {
            id: "e1_117",
            department: "電機電子群",
            grade: 1,
            subject: "電子學 (117)",
            teacherEmail: "t1049@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_118",
            department: "電機電子群",
            grade: 1,
            subject: "數位邏輯 (118)",
            teacherEmail: "t1103@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_119",
            department: "電機電子群",
            grade: 1,
            subject: "單晶片控制 (119)",
            teacherEmail: "t1086@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群一各班",
            hasListeningExam: false,
        },
        {
            id: "e1_120",
            department: "電機電子群",
            grade: 2,
            subject: "微處理機 (120)",
            teacherEmail: "t1028@ksvs.kh.edu.tw",
            fileUrl: "",
            markingType: "",
            pageCount: 0,
            applicableClass: "電機電子群二各班",
            hasListeningExam: false,
        },
    ],
    exam2: [],
    exam3: [],
    exam4: [],
};
