// src/services/mockData.js

export const mockData = {
  settings: [
    {
      id: "1",
      academicYear: "113",
      semester: "1",
      examName: "第三次定期考",
      uploadStart: "2026-03-25T00:00:00",
      uploadEnd: "2026-04-28T12:35:59",
    },
    {
      id: "2",
      academicYear: "113",
      semester: "1",
      examName: "第二次定期考",
      uploadStart: "2025-11-01T00:00:00",
      uploadEnd: "2025-11-15T23:59:59",
    },
  ],
  users: [
    // Admins
    {
      email: "admin@ksvs.kh.edu.tw",
      teacherCode: "A001",
      name: "王大明",
      role: "admin",
    },
    {
      email: "director@ksvs.kh.edu.tw",
      teacherCode: "A002",
      name: "林主任",
      role: "admin",
    },
    // Teachers
    {
      email: "t1001@ksvs.kh.edu.tw",
      teacherCode: "T1001",
      name: "陳國文",
      role: "teacher",
    },
    {
      email: "t1002@ksvs.kh.edu.tw",
      teacherCode: "T1002",
      name: "李數學",
      role: "teacher",
    },
    {
      email: "t1003@ksvs.kh.edu.tw",
      teacherCode: "T1003",
      name: "張物理",
      role: "teacher",
    },
    {
      email: "t1004@ksvs.kh.edu.tw",
      teacherCode: "T1004",
      name: "吳健康",
      role: "teacher",
    },
    {
      email: "t2208@ksvs.kh.edu.tw",
      teacherCode: "T2208",
      name: "劉測試",
      role: "teacher",
    }, // Testing account
  ],
  classes: [
    { id: "101", name: "機械一甲" },
    { id: "102", name: "資訊一甲" },
    { id: "201", name: "電機二甲" },
    { id: "301", name: "電子三甲" },
  ],
  exam1: [
    {
      id: "e1_1",
      department: "一般科目",
      grade: 1,
      subject: "英語文",
      teacherEmail: "t1001@ksvs.kh.edu.tw",
      fileUrl: "",
      markingType: "",
      pageCount: 0,
      applicableClass: "機械一甲, 資訊一甲, 電子一甲, 電機一乙",
      hasListeningExam: false,
    },
    {
      id: "e1_5",
      department: "一般科目",
      grade: 1,
      subject: "國語文",
      teacherEmail: "t1001@ksvs.kh.edu.tw",
      fileUrl: "",
      markingType: "人工閱卷+電腦閱卷",
      pageCount: 0,
      applicableClass: "全一年級",
    },
    {
      id: "e1_6",
      department: "一般科目",
      grade: 2,
      subject: "歷史",
      teacherEmail: "t1001@ksvs.kh.edu.tw",
      fileUrl: "https://example.com/mock.pdf",
      markingType: "電腦閱卷",
      pageCount: 2,
      applicableClass: "二甲, 二乙, 二丙",
    },
    {
      id: "e1_2",
      department: "一般科目",
      grade: 1,
      subject: "數學",
      teacherEmail: "t1002@ksvs.kh.edu.tw",
      fileUrl: "",
      markingType: "",
      pageCount: 0,
      applicableClass: "電機一甲",
    },
    {
      id: "e1_3",
      department: "一般科目",
      grade: 1,
      subject: "健康與護理",
      teacherEmail: "t1004@ksvs.kh.edu.tw",
      fileUrl: "https://example.com/pdf",
      markingType: "電腦閱卷",
      pageCount: 2,
      applicableClass: "全一年級",
    },
    {
      id: "e1_4",
      department: "一般科目",
      grade: 1,
      subject: "物理",
      teacherEmail: "t1003@ksvs.kh.edu.tw",
      fileUrl: "",
      markingType: "",
      pageCount: 0,
      applicableClass: "電子一甲",
    },
  ],
  exam2: [],
  exam3: [],
  exam4: [],
};
